applications:
    php:
        type: php
        ports:
            8000: 8000
        after_script:
            php -S 0.0.0.0:8000 -t /app/web
        volumes:
            .: /app

binaries:
    npm:
        type: npm

    composer:
        type: composer

    bower:
        type: bower
