language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower'
  - 'bower install'
sudo: false # Use Docker for quicker builds, see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
